{% set version = "6.0.12.20250809" %}

package:
  name: types-pyyaml
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-pyyaml/types_pyyaml-{{ version }}.tar.gz
    sha256: af4a1aca028f18e75297da2ee0da465f799627370d74073e96fee876524f61b5
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/yaml-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for PyYAML
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
